"""empty message

Revision ID: 3a50e0641932
Revises: cf059a742791
Create Date: 2021-08-31 17:31:23.146412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a50e0641932'
down_revision = 'cf059a742791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.String(), nullable=False),
    sa.Column('venueid', sa.Integer(), nullable=False),
    sa.Column('artistid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venueid'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('looking_talent', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('looking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'description')
    op.drop_column('Venue', 'looking_talent')
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'website')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'looking_talent')
    op.drop_column('Artist', 'website')
    op.drop_table('Show')
    # ### end Alembic commands ###
